services:
  httpclock:
    image: ghcr.io/yanorei32/http-clock:0.3.1
    hostname: httpclock
    container_name: httpclock__httpclock

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2025.2.1
    hostname: cloudflared
    container_name: httpclock__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 512m

    networks:
      default:

networks:
  default:
    name: httpclock__default
